### ISSUE TITLE
Document how musl toolchains were built

### ISSUE THREAD

**Issue by henderkes** [crazywhalecc/static-php-cli-hosted#2]
Upload a readme, config.mak and Dockerfiles in the file tree?
https://dl.static-php.dev/static-php-cli/deps/musl-toolchain/

Or maybe even better a build script that creates both?

**Comment by crazywhalecc** [comment]
Written in https://github.com/crazywhalecc/static-php-cli-docs/commit/b466a35ecc570afd2c548d3217d2a721b55ab01e
