### ISSUE TITLE
is ${{ secrets.S_GITHUB_TOKEN }} a typo? should be  ${{ secrets.GITHUB_TOKEN }}?

### ISSUE THREAD

**Issue by gemini133** [crazywhalecc/static-php-cli-hosted#5]
Hi
Thanks for your static-php-cli project.
I forked this repo and play it around.
I find it's always 403 error when downloading sources.
I change to `${{ secrets.GITHUB_TOKEN }}` and everything works.

I'm not familiar github actions and it looks like your repo "actions" are working.
not sure if it's a mistake...

**Comment by crazywhalecc** [comment]
I used my own github token for hosted repo, its name is indeed `S_GITHUB_TOKEN`. I often have issue on token limitation, that's why I use another independent secret to pass my token. Just add your own token to project actions secret `S_GITHUB_TOKEN` should be fine.
